import { lines } from "@/constants/lines";

const RER_data:LineSettings[] = [
    {
        name:"A",
        slug:"RER_A",
        icon:lines.A,
        checked:false
    },
    {
        name:"B",
        slug:"RER_B",
        icon:lines.B,
        checked:false
    },
    {
        name:"C",
        slug:"RERC_SNCF",
        icon:lines.C,
        checked:false
    },
    {
        name:"D",
        slug:"RERD_SNCF",
        icon:lines.D,
        checked:false
    },
    {
        name:"E",
        slug:"RERE_SNCF",
        icon:lines.E,
        checked:false
    }
]

const Transilien_data:LineSettings[] = [
    {
        name:"H",
        slug:"LigneH_SNCF",
        icon:lines.H,
        checked:false
    },
    {
        name:"J",
        slug:"LIGNEJ_SNCF",
        icon:lines.J,
        checked:false
    },
    {
        name:"K",
        slug:"LigneK_SNCF",
        icon:lines.K,
        checked:false
    },
    {
        name:"L",
        slug:"LIGNEL_sncf",
        icon:lines.L,
        checked:false
    },
    {
        name:"N",
        slug:"lignesNetU_SNCF",
        icon:lines.N,
        checked:false
    },
    {
        name:"P",
        slug:"LIGNEP_SNCF",
        icon:lines.P,
        checked:false
    },
    {
        name:"R",
        slug:"LIGNER_SNCF",
        icon:lines.R,
        checked:false
    },
    {
        name:"U",
        slug:"lignesNetU_SNCF",
        icon:lines.U,
        checked:false
    },
    {
        name:"V",
        slug:"LIGNEV_SNCF",
        icon:lines.V,
        checked:false
    }
]

const Metro_data:LineSettings[] = [
    {
        name:"M1",
        slug:"Ligne1_RATP",
        icon:lines.M1,
        checked:false
    },
    {
        name:"M2",
        slug:"Ligne2_RATP",
        icon:lines.M2,
        checked:false
    },
    {
        name:"M3",
        slug:"Ligne3_RATP",
        icon:lines.M3,
        checked:false
    },
    {
        name:"M3bis",
        slug:"Ligne3_RATP",
        icon:lines.M3bis,
        checked:false
    },
    {
        name:"M4",
        slug:"Ligne4_RATP",
        icon:lines.M4,
        checked:false
    },
    {
        name:"M5",
        slug:"Ligne5_RATP",
        icon:lines.M5,
        checked:false
    },
    {
        name:"M6",
        slug:"Ligne6_RATP",
        icon:lines.M6,
        checked:false
    },
    {
        name:"M7",
        slug:"Ligne7_RATP",
        icon:lines.M7,
        checked:false
    },
    {
        name:"M7bis",
        slug:"Ligne7_RATP",
        icon:lines.M7bis,
        checked:false
    },
    {
        name:"M8",
        slug:"Ligne8_RATP",
        icon:lines.M8,
        checked:false
    },
    {
        name:"M9",
        slug:"Ligne9_RATP",
        icon:lines.M9,
        checked:false
    },
    {
        name:"M10",
        slug:"Ligne10_RATP",
        icon:lines.M10,
        checked:false
    },
    {
        name:"M11",
        slug:"Ligne11_RATP",
        icon:lines.M11,
        checked:false
    },
    {
        name:"M12",
        slug:"Ligne12_RATP",
        icon:lines.M12,
        checked:false
    },
    {
        name:"M13",
        slug:"Ligne13_RATP",
        icon:lines.M13,
        checked:false
    },
    {
        name:"M14",
        slug:"Ligne14_RATP",
        icon:lines.M14,
        checked:false
    }
]

const Tram_data:LineSettings[] = [
    {
        name:"T1",
        slug:"T1_RATP",
        icon:lines.T1,
        checked:false
    },
    {
        name:"T2",
        slug:"T2_RATP",
        icon:lines.T2,
        checked:false
    },
    {
        name:"T3a",
        slug:"T3a_RATP",
        icon:lines.T3a,
        checked:false
    },
    {
        name:"T3b",
        slug:"T3b_RATP",
        icon:lines.T3b,
        checked:false
    },
    {
        name:"T4",
        slug:"T4_IDFM",
        icon:lines.T4,
        checked:false
    },
    {
        name:"T5",
        slug:"T5_RATP",
        icon:lines.T5,
        checked:false
    },
    {
        name:"T6",
        slug:"T6_RATP",
        icon:lines.T6,
        checked:false
    },
    {
        name:"T7",
        slug:"T7_RATP",
        icon:lines.T7,
        checked:false
    },
    {
        name:"T8",
        slug:"T8_RATP",
        icon:lines.T8,
        checked:false
    },
    {
        name:"T9",
        slug:"T9_IDFM",
        icon:lines.T9,
        checked:false
    },
    {
        name:"T10",
        slug:"T10_IDFM_",
        icon:lines.T10,
        checked:false
    },
    {
        name:"T11",
        slug:"T11_IDFM",
        icon:lines.T11,
        checked:false
    },
    {
        name:"T12",
        slug:"T12_IDFM",
        icon:lines.T12,
        checked:false
    },
    {
        name:"T13",
        slug:"T13_IDFM",
        icon:lines.T13,
        checked:false
    },
    {
        name:"T14",
        slug:"T14_IDFM",
        icon:lines.T14,
        checked:false
    }
]

// pour le Câble C1, se référer au territoire Marne et Seine
// DSP et MP arrivent bientôt

export const lines_data:LineSettings[] = RER_data.concat(Transilien_data,Metro_data,Tram_data)